---
title: "Mercado de passageiros"
---

```{r, child="_chunk_opts.Rmd"}
```

## {.tabset .tabset-pills}

### Passageiros transportados (em milhões)
<br>

#### **Mercado agregado**
```{r}
yearly_market_plots$pax
monthly_market_plots$pax
```
<br>
<br>

#### **Por companhias**
```{r}
monthly_dom_companies_plots$pax
monthly_intl_companies_plots$pax
```
<br>


### Demanda (assentos-km)
<br>

#### **Mercado agregado**
```{r}
yearly_market_plots$rpk
monthly_market_plots$rpk
```
<br>
<br>

#### **Por companhias**
```{r}
monthly_dom_companies_plots$rpk
monthly_intl_companies_plots$rpk
```
<br>


### *Market-share*
<br>

#### **Mercado agregado**
```{r}
share_plots$dom_pax
share_plots$intl_pax
```
<br>
<br>

#### **Por companhias**
```{r}
monthly_dom_companies_plots$pax_share
monthly_intl_companies_plots$pax_share
```
<br>

### *Load factor* (em %)
```{r}
yearly_market_plots$load
monthly_market_plots$load
```
<br>

### Decolagens
<br>

#### **Mercado agregado**
```{r}
yearly_market_plots$departures
monthly_market_plots$departures
```
<br>
<br>

#### **Por companhias**
```{r}
monthly_dom_companies_plots$departures
```

