name: Data retriever

on:
  push:
    branches:
      - master

  workflow_dispatch:
  
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 2 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image 
      run: |
        docker build -t avmkt .
        ls -a
        pwd
        
    - name: Run image
      run: |
        docker run -v $(pwd):/home/avmkt avmkt
        
    - name: Check produced files
      run: |
        ls -a -l
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add docs/
        git commit -m "Update site" -a
       
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch:  'gh-pages'
        force:  true 
        github_token: ${{ secrets.GITHUB_TOKEN }}
