name: Data retriever

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image 
      run: |
        docker build -t avmkt .
        ls -a
        pwd
        
    - name: Run image
      run: |
        docker run -v $(pwd):/home/avmkt avmkt
        
    - name: Check produced files
      run: |
        ls -a -l
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add *.html
        git add site_libs/
        git commit -m "Update site" -a
       
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Latest run
        base: gh-pages
