name: Data retriever

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build docker image 
      run: |
        docker build -t avmkt .
        ls -a
        pwd
        
    - name: Run image
      run: |
        docker run -v $(pwd):/home/avmkt avmkt
        
    - name: Check produced files
      run: |
        ls -a -l
       
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: Latest run
        branch: update-data
        base: gh-pages
